---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sparkingasia/public_html/timetracker
    - /usr/bin/rsync -a --delete --exclude=.git --exclude=.env --exclude=node_modules --exclude=vendor --exclude=public/storage --exclude=storage/app/public --exclude=storage/framework/cache/data --exclude=storage/framework/sessions --exclude=storage/framework/views --exclude=storage/logs/*.log ./ $DEPLOYPATH/
    - cd $DEPLOYPATH
    - composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
    - npm ci
    - npm run build
    - php artisan migrate --force
    - php artisan storage:link
    - php artisan optimize
