<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (Schema::hasTable('tracking_sessions')) {
            return;
        }

        Schema::create('tracking_sessions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->foreignId('client_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('upwork_profile_id')->nullable()->constrained('upwork_profiles')->nullOnDelete();
            $table->string('work_type', 50)->nullable();
            $table->text('task_note')->nullable();
            $table->timestamp('started_at');
            $table->timestamp('stopped_at')->nullable();
            $table->timestamp('last_heartbeat_at')->nullable();
            $table->unsignedInteger('total_seconds')->default(0);
            $table->unsignedTinyInteger('activity_percent')->default(0);
            $table->string('status', 20)->default('active'); // active | stopped | abandoned
            $table->string('source', 20)->default('desktop'); // desktop | manual
            $table->string('device_name')->nullable();
            $table->string('platform', 30)->nullable(); // win32 | darwin | linux
            $table->string('app_version', 30)->nullable();
            $table->string('client_uuid', 64)->nullable(); // local UUID generated by desktop app for offline reconciliation
            $table->timestamps();

            $table->index(['user_id', 'started_at']);
            $table->index(['status', 'last_heartbeat_at']);
            $table->unique(['user_id', 'client_uuid']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('tracking_sessions');
    }
};
