export const themeColors = {
  sparkingasia: {
    primary: 'yellow-500',
    primaryHover: 'yellow-600',
    primaryLight: 'yellow-100',
    primaryBg: 'yellow-50',
    text: 'green-700',
    ring: 'yellow-400',
    gradientFrom: 'yellow-100',
    gradientTo: 'green-100',
    secondary: 'green-600',
    secondaryHover: 'green-700',
    accent: 'green-500',
  },
  lime: {
    primary: 'lime-500',
    primaryHover: 'lime-600',
    primaryLight: 'lime-100',
    primaryBg: 'lime-50',
    text: 'green-800',
    ring: 'lime-400',
    gradientFrom: 'lime-100',
    gradientTo: 'green-100',
    secondary: 'green-600',
    secondaryHover: 'green-700',
    accent: 'lime-500',
  },
  emerald: {
    primary: 'emerald-600',
    primaryHover: 'emerald-700',
    primaryLight: 'emerald-100',
    primaryBg: 'emerald-50',
    text: 'emerald-700',
    ring: 'emerald-500',
    gradientFrom: 'emerald-100',
    gradientTo: 'emerald-50',
  },
  indigo: {
    primary: 'indigo-600',
    primaryHover: 'indigo-700',
    primaryLight: 'indigo-100',
    primaryBg: 'indigo-50',
    text: 'indigo-700',
    ring: 'indigo-500',
    gradientFrom: 'indigo-100',
    gradientTo: 'indigo-50',
  },
  rose: {
    primary: 'rose-600',
    primaryHover: 'rose-700',
    primaryLight: 'rose-100',
    primaryBg: 'rose-50',
    text: 'rose-700',
    ring: 'rose-500',
    gradientFrom: 'rose-100',
    gradientTo: 'rose-50',
  },
  amber: {
    primary: 'amber-600',
    primaryHover: 'amber-700',
    primaryLight: 'amber-100',
    primaryBg: 'amber-50',
    text: 'amber-700',
    ring: 'amber-500',
    gradientFrom: 'amber-100',
    gradientTo: 'amber-50',
  },
};

export function getThemeClasses(theme: keyof typeof themeColors) {
  const colors = themeColors[theme];
  return {
    primary: `bg-${colors.primary} text-white hover:bg-${colors.primaryHover}`,
    primaryOutline: `border-${colors.primary} text-${colors.text} hover:bg-${colors.primaryLight}`,
    text: `text-${colors.text}`,
    background: `bg-${colors.primaryBg}`,
    ring: `ring-${colors.ring}`,
    gradient: `bg-gradient-to-br from-${colors.gradientFrom} to-${colors.gradientTo}`,
  };
}